# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 소개
    url: /
    weight: 10
  - name: 연구실적
    url: research/
    weight: 15
  - name: 경험
    url: experience/
    weight: 20
  - name: 프로젝트
    url: projects/
    weight: 30
